- src/configs/recommended.ts
> load correct plugin in config

- package-lock.json
- package.json
- src/template-analyzer.ts
just doing a version update since its been a while.
> chore: bump dependencies

- package-lock.json
- package.json
left over from previous dependency update
> chore: remove unused typescript plugin

- src/rules/attribute-value-entities.ts
- src/rules/binding-positions.ts
- src/rules/no-duplicate-template-bindings.ts
- src/rules/no-invalid-html.ts
- src/rules/no-legacy-template-syntax.ts
- src/rules/no-property-change-update.ts
- src/rules/no-template-bind.ts
- src/rules/no-template-map.ts
- src/rules/no-useless-template-literals.ts
- src/rules/no-value-attribute.ts
- src/test/rules/attribute-value-entities_test.ts
- src/test/rules/binding-positions_test.ts
- src/test/rules/no-duplicate-template-bindings_test.ts
- src/test/rules/no-invalid-html_test.ts
- src/test/rules/no-legacy-template-syntax_test.ts
- src/test/rules/no-property-change-update_test.ts
- src/test/rules/no-template-bind_test.ts
- src/test/rules/no-template-map_test.ts
- src/test/rules/no-useless-template-literals_test.ts
- src/test/rules/no-value-attribute_test.ts
> chore: fix every typo

- .eslintrc.json
- .gitignore
- .prettierrc
- .travis.yml
- .vscode/settings.json
- README.md
- package-lock.json
- package.json
- src/index.ts
- src/rules/attribute-value-entities.ts
- src/rules/binding-positions.ts
- src/rules/no-duplicate-template-bindings.ts
- src/rules/no-invalid-html.ts
- src/rules/no-legacy-template-syntax.ts
- src/rules/no-property-change-update.ts
- src/rules/no-template-bind.ts
- src/rules/no-template-map.ts
- src/rules/no-useless-template-literals.ts
- src/rules/no-value-attribute.ts
- src/template-analyzer.ts
- src/test/rules/attribute-value-entities_test.ts
- src/test/rules/no-invalid-html_test.ts
- src/test/rules/no-legacy-template-syntax_test.ts
- src/test/rules/no-property-change-update_test.ts
- src/test/rules/no-template-bind_test.ts
- src/test/rules/no-template-map_test.ts
- src/test/rules/no-useless-template-literals_test.ts
- src/test/rules/no-value-attribute_test.ts
- src/util.ts
Adds useful scripts and configuration
> chore: update scripts

- README.md
Fixes #39 
Also adjusts the headers
> Update README.md to have Configuration usage example

- README.md
- docs/rules/no-template-arrow.md
- src/rules/no-template-arrow.ts
- src/test/rules/no-template-arrow_test.ts
- src/test/rules/no-template-bind_test.ts
Moved some of bind into its own rule.
Potential solution to #35 , will review once im back in the country next week.
> rule: no-template-arrow

- src/configs/all.ts
- src/configs/recommended.ts
- src/index.ts
> Config for all rules enabled

- src/rules/attribute-value-entities.ts
- src/template-analyzer.ts
- src/test/rules/attribute-value-entities_test.ts
Fixes #74 
i've accounted for quotes-within-quotes but i dont think its actually possible as the parser would fail long before it reaches us.
can't hurt to check though i suppose
> allow quotes in attributes, account for unescaped delims

- package-lock.json
- package.json
- src/rules/no-property-change-update.ts
- src/rules/no-useless-template-literals.ts
- src/test/rules/no-property-change-update_test.ts
- src/test/rules/no-useless-template-literals_test.ts
- src/test/util_test.ts
- src/util.ts
Still need to get the coverage back up because i added a bunch of complexity to compute property maps.
> Add some lit v2 support and tidy up useless-literals rule

- .github/workflows/main.yml
- .travis.yml
- package.json
> Move CI to GitHub Actions

- src/configs/all.ts
> add quoted-expressions to all config

- src/rules/no-value-attribute.ts
- src/test/rules/no-value-attribute_test.ts
> add fixer to no-value-attribute

- custom_types/espree.d.ts
- package-lock.json
- package.json
- src/template-analyzer.ts
- src/test/template-analyzer_test.ts
This is mostly a helper for third-party consumers of our template analyzer (e.g. openwc).
It allows you to get the value of a given attribute, whether it be a string or an expression.
cc @stramel
> add getAttributeValue helper

- src/test/rules/no-invalid-html_test.ts
- src/util.ts
Fixes #66
Still not perfect ofc. I'm hoping eventually the analyser the lit team are working on will make this a much more stable rule.
> fix: stricter attribute binding detection

- README.md
- docs/rules/prefer-nothing.md
- src/rules/prefer-nothing.ts
- src/test/rules/prefer-nothing_test.ts
Fixes #139 
@stramel can you possibly review?
> feat: add new prefer-nothing rule

- .eslintrc.json
- README.md
- docs/rules/value-after-constraints.md
- src/configs/all.ts
- src/rules/value-after-constraints.ts
- src/test/rules/value-after-constraints_test.ts
Fixes #109
cc @stramel @claviska
> feat: new value-after-constraints rule

- src/rules/quoted-expressions.ts
- src/test/rules/quoted-expressions_test.ts
> fix (quote-expressions): only match attributes

- src/rules/value-after-constraints.ts
> fix: account for nullish attr locations

- docs/rules/no-native-attributes.md
- src/configs/all.ts
- src/rules/no-native-attributes.ts
- src/test/rules/no-native-attributes.ts
- src/test/rules/no-native-attributes_test.ts
- src/util.ts
@43081j Gonna have to ask you to help satisfy typescript on this one 🙃🫠
> feat: no native attributes

- src/rules/attribute-names.ts
- src/test/rules/attribute-names_test.ts
I have added a test and corrected the issue exactly as you suggested.
See https://github.com/43081j/eslint-plugin-lit/issues/202
> Fix for #202

- LICENSE
- package-lock.json
fixes #220 
apparently the copyright year should be when it was first published
> chore: add license
