43081j/eslint-plugin-lit

docs/attribute-value-entities.md, src/rules/attribute-value-entities.ts, src/test/rules/attribute-value-entities_test.ts
Fixes #1.
Disallows unencoded reserved characters in attribute values:
`&`, `"`, `<` and `>`.
=> new rule: attribute-value-entities

README.md, docs/no-duplicate-template-bindings.md, docs/no-legacy-template-syntax.md, docs/no-template-bind.md, docs/no-template-map.md, docs/no-useless-template-literals.md, src/rules/no-duplicate-template-bindings.ts, src/rules/no-legacy-template-syntax.ts, src/rules/no-template-bind.ts, src/rules/no-template-map.ts, src/rules/no-useless-template-literals.ts, src/test/rules/no-duplicate-template-bindings_test.ts, src/test/rules/no-legacy-template-syntax_test.ts, src/test/rules/no-template-bind.ts, src/test/rules/no-template-map_test.ts, src/test/rules/no-useless-template-literals_test.ts
The rules were a bit badly named, these seem to follow the same conventions eslint's naming does.
=> rename rules to follow eslint

README.md, docs/no-invalid-html.md, src/rules/no-invalid-html.ts, src/test/rules/no-invalid-html_test.ts
This will be an easy way to validate that templates contain valid HTML.
the most common error we all make is this, I think, so should be an easy one to catch.
=> new: no-invalid-html rule

docs/no-template-bind.md, src/rules/no-template-bind.ts, src/test/rules/no-template-bind_test.ts
When Polymer/lit-html#523 is merged along with an associated lit-element PR, this will be the correct documentation/warning.
We no longer have to bind our methods directly at that point, lit will do it for us.
=> document lit's auto-binding

README.md, docs/no-value-attribute.md, src/rules/no-value-attribute.ts, src/test/rules/no-value-attribute_test.ts, src/util.ts
Fixes #20.
Introduces a rule for disallowing use of the `value` attribute with
bindings.
=> rule: no-value-attribute rule

.eslintrc.json, package-lock.json, package.json
gets rid of an audit message and moves to the new typescript-eslint packages.
=> chore: bump deps

docs/no-legacy-template-syntax.md
After now is equivalent to the before snippet, just using the new syntax
=> docs: Update syntax to align before and after

docs/rules/binding-positions.md, src/rules/binding-positions.ts, src/test/rules/binding-positions_test.ts
Fixes #42.
This disallows the following binding position:
```ts
html``;
```
It allows (for example):
```ts
html`${binding}`;
```
=> binding-positions: add HTML comment assertions

docs/rules/binding-positions.md, src/rules/binding-positions.ts, src/test/rules/binding-positions_test.ts
Fixes #45.
We just check for `${foo}/>`.
I can see this rule possibly having some issues (unrelated to this change) because it doesn't check it is inside a HTML tag. Would be a good change to add in future
=> binding-positions: detect self-closing tag problems

src/rules/attribute-value-entities.ts, src/rules/binding-positions.ts, src/template-analyzer.ts, src/test/rules/attribute-value-entities_test.ts, src/test/rules/binding-positions_test.ts
Fixes #48.
Changed the pattern to account for correctly encoded entities (who knew, they have an `&` in them.. 🤦‍♂ )
=> attribute-value-entities: allow `&amp;` and friends

README.md, docs/rules/no-invalid-escape-sequences.md, src/rules/no-invalid-escape-sequences.ts, src/test/rules/no-invalid-escape-sequences_test.ts
This disallows octal escape sequences in tagged templates.
Fixes #44.
@justinfagnani could you let me know if this seems sufficient for the issue you raised? or are there more sequences than octal we should detect?
cc @stramel
=> new rule: no-invalid-escape-sequences

src/template-analyzer.ts, src/test/rules/attribute-value-entities_test.ts
Fixes #51 
It turns out a valueless attribute was being flagged as an invalid entity:
```html
<x-foo ihavenovalue>
```
was parsing its value as the end `>` but should have been `""`.
=> template-analyzer: support valueless attributes

src/template-analyzer.ts, src/test/rules/attribute-value-entities_test.ts
Parse5 does some questionably confusing transforms to the AST when using SVG elements.
viewbox becomes viewBox.
in every other element for every attribute, they are left lowercase, except in svg...
Fixes #54
=> template-analyzer: use lowercase attributes for location info

package-lock.json, package.json, src/test/rules/attribute-value-entities_test.ts, src/test/rules/binding-positions_test.ts, src/test/rules/no-duplicate-template-bindings_test.ts, src/test/rules/no-invalid-escape-sequences_test.ts, src/test/rules/no-invalid-html_test.ts, src/test/rules/no-legacy-template-syntax_test.ts, src/test/rules/no-private-properties_test.ts, src/test/rules/no-property-change-update_test.ts, src/test/rules/no-template-arrow_test.ts, src/test/rules/no-template-bind_test.ts, src/test/rules/no-template-map_test.ts, src/test/rules/no-useless-template-literals_test.ts, src/test/rules/no-value-attribute_test.ts
internally we can use eslint 6.x pretty easily, just needed to set the tests to resolve the babel parser and specify a minimum ecma version.
Fixes #53
=> update devDeps to eslint6

src/template-analyzer.ts, src/test/rules/attribute-value-entities_test.ts
Fixes #57 
Again parse5 does some special case witchcraft around namespaced XML attributes (specific ones..)
i resolved this by checking if a prefix has been defined and using it if so. bit of a pain as they may do other transforms too which we just haven't been tripped up by yet, but adding a catch all would mean we miss those cases (silently caught errors).
=> template-analyzer: support prefixed xml attribs

src/template-analyzer.ts, src/test/rules/attribute-value-entities_test.ts, src/test/rules/no-duplicate-template-bindings_test.ts, src/test/rules/no-invalid-html_test.ts, src/test/rules/no-legacy-template-syntax_test.ts, src/test/rules/no-private-properties_test.ts, src/test/rules/no-value-attribute_test.ts, src/util.ts
=> fix: report on correct location instead of entire quasi

README.md, package-lock.json, package.json, src/rules/no-useless-template-literals.ts, src/template-analyzer.ts
This also replaces `watch` with `nodemon` for the `start` npm script (to watch for changes).
There were vulns in `watch` dependency tree and it seems less maintained, though nodemon is a fair chunk bigger...
=> update readme and dependencies

src/rules/no-useless-template-literals.ts, src/test/rules/no-useless-template-literals_test.ts
We were getting the expression after the position, rather than _immediately_ after the position.
@stramel if you get chance could you double check this logic:
Given the position of an attribute, find the quasi (string) which satisfies one of:
* Starts before the attribute's start line but ends after the attribute's end line
* Starts on the attribute's start line but before it (so must contain it)
* Ends on the attribute's start line but after it
Then return the expression after that quasi.
Confusing logic, basically though it meant that all attributes in the quasi would return the expression i think...
```html
<x-foo
attr="abc"
.prop=${v}>
```
Both would return an expression using this logic. Even though only prop should.
Because the previous logic made my brain melt a bit, i removed it …
=> fix no-useless-template-literals node position resolution

src/rules/attribute-value-entities.ts, src/rules/no-duplicate-template-bindings.ts, src/rules/no-invalid-html.ts, src/rules/no-legacy-template-syntax.ts, src/rules/no-private-properties.ts, src/rules/no-useless-template-literals.ts, src/rules/no-value-attribute.ts, src/template-analyzer.ts, src/test/rules/no-duplicate-template-bindings_test.ts, src/test/rules/no-invalid-html_test.ts, src/test/rules/no-legacy-template-syntax_test.ts, src/test/rules/no-private-properties_test.ts
`resolveLocation` has been left alone for quite some time because its already so delicate.
though it turns out @stramel discovered many of our errors are reported with the wrong position information and tests didn't catch this as they either had no end column, or we just didn't check that the asserted column actually was the right one! 🤦‍♂️ 
nobody understood this function and i struggled to remember too, so i deleted it.
i've rewritten it from scratch based on offsets, with `getLocFromIndex` being our saviour here 🥳  this means we don't need to calculate line changes, account for multi-line expressions, quasis, etc. that was where most of the complexity lived before.
here's how we calculate it now:
* Loop through the quasis
* Every time we see an expression, increment a correction number …
=> replace resolveLocation with a simpler implementation

docs/rules/prefer-static-styles.md, package-lock.json, package.json, src/configs/all.ts, src/rules/prefer-static-styles.ts, src/test/rules/no-property-change-update_test.ts, src/test/rules/prefer-static-styles_test.ts
Fixes #86 
If `always` is set (default), it allows:
* Any assignment to an `adoptedStylesheets` property of anything (lazily since its unlikely anyone will ever name a property that which doesn't take adopted stylesheets...)
* Static styles property of a lit element class
It disallows:
* Style tags inside templates
=> rule: prefer-static-styles

src/rules/no-invalid-escape-sequences.ts, src/test/rules/no-invalid-escape-sequences_test.ts, tsconfig.json
Fixes #101 
Fixes #106
@stramel would you mind double checking this in an editor? we need to be sure that `+1` is right again 😂 
i _think_ it is...
```ts
html`foo`
// quasi.range[0] would be the first backtick (`)
// lets say we match `/o/`, the first regex index will be 1 i suppose
// so range[0] + 1 would give us the `f` but we want the `o`, so we +1 to account for the backtick
```
=> highlight escape sequence rather than quasi

.eslintrc.json, .github/workflows/main.yml, package.json, src/rules/attribute-value-entities.ts, src/rules/no-useless-template-literals.ts, src/template-analyzer.ts, src/util.ts, tsconfig.json
As brought up in the issue, optional chaining operator is not available less than node v14 and node v12 is still in LTS.
Fixes #110
=> Remove optional chaining operator

package-lock.json, package.json, src/rules/attribute-value-entities.ts, src/rules/binding-positions.ts, src/rules/no-duplicate-template-bindings.ts, src/rules/no-invalid-escape-sequences.ts, src/rules/no-invalid-html.ts, src/rules/no-legacy-imports.ts, src/rules/no-legacy-template-syntax.ts, src/rules/no-private-properties.ts, src/rules/no-property-change-update.ts, src/rules/no-template-arrow.ts, src/rules/no-template-bind.ts, src/rules/no-template-map.ts, src/rules/no-useless-template-literals.ts, src/rules/no-value-attribute.ts, src/rules/prefer-static-styles.ts, src/rules/quoted-expressions.ts, src/template-analyzer.ts, src/test/template-analyzer_test.ts
Fixes #115 
This is another utility one really, adding the ability for template analyzer to parse HTML documents.
It always parses as a fragment at the min, which means something like this:
```html
<html><body>Foo</body></html>
```
would be parsed as `Foo` essentially.
by adding this switch in the constructor, we'll parse it as a document instead, maintaining the html/body tags.
cc @stramel 
Part im not sure of is if the condition is strong enough, i.e. checking for `includes('<html')`. seems incredibly unlikely anyone can ever have a `<html-something-else` tag so maybe its ok?
Also looks like prettier being bumped now decided to re-format URLs
=> add support for parsing HTML documents

.eslintrc.json
* Enables [eslint-plugin/require-meta-docs-description](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-description.md) with the prefixes used by the rules in this plugin
* Enables [eslint-plugin/require-meta-docs-url](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-url.md) with the pattern that enables the rule to automatically autofix the right URL in each rule
=> chore: enable `eslint-plugin/require-meta-docs-description` and `eslint-plugin/require-meta-docs-url` rules internally

.github/workflows/main.yml
Quick PR for CI changes:
- Drop testing in Node 15 and add Node 18.
- Upgrade GitHub actions to the latest versions.
=> chore: Add Node 18 to CI and upgrade GitHub actions

README.md, docs/rules/no-this-assign-in-render.md, src/rules/no-this-assign-in-render.ts, src/test/rules/no-this-assign-in-render_test.ts
Fixes #90
@stramel @bennypowers could you both take a look if you get time? and be sure it all makes sense.
this is a very similar rule to `no-property-change-update` but instead of specifically looking for observed properties, it disallows _all_ `this` assignments (in the render method too rather than the update method).
=> feat: new rule no-this-assign-in-render

docs/rules/no-property-change-update.md, src/rules/no-property-change-update.ts, src/test/rules/no-property-change-update_test.ts
It is perfectly valid to mutate properties in `update` as long as you call `super.update()` _at the end_. This rule incorrectly marked these cases as invalid.
It now detects mutations to observed properties _after_ `super.update` has been called and flags those as problems.
Fixes #62
maybe cc @larsdenbakker to check that i worded the docs correctly.
really the rule should be renamed but it'd be a breaking change and seems close enough as it is now.
=> feat: rework no-property-change-update rule

src/configs/all.ts, src/rules/attribute-value-entities.ts, src/rules/ban-attributes.ts, src/rules/binding-positions.ts, src/rules/no-duplicate-template-bindings.ts, src/rules/no-invalid-escape-sequences.ts, src/rules/no-invalid-html.ts, src/rules/no-legacy-imports.ts, src/rules/no-legacy-template-syntax.ts, src/rules/no-private-properties.ts, src/rules/no-property-change-update.ts, src/rules/no-template-arrow.ts, src/rules/no-template-bind.ts, src/rules/no-template-map.ts, src/rules/no-this-assign-in-render.ts, src/rules/no-useless-template-literals.ts, src/rules/no-value-attribute.ts, src/rules/prefer-nothing.ts, src/rules/prefer-static-styles.ts, src/rules/quoted-expressions.ts
The `recommended` flag isn't useful afaict since the recommended config defines what we want, not the flag.
Similarly, the `category` property seems deprecated, so has been removed from all rules.
Also updated the `all` config to have the new rules in.
=> fix: set all recommended flags as false, update configs/all

src/rules/no-native-attributes.ts
The upcoming `popover` feature (spec PR: https://github.com/whatwg/html/pull/8221, explainer: https://open-ui.org/components/popup.research.explainer) adds `popover` as a global attribute to all HTMLElements. There is high confidence of good webcompat with this attribute (it used to be called `popup` but that had webcompat issues).
I think it would be good for `eslint-plugin-lit` to also introduce this. WebKit's standard position on `popover` is "support" (https://github.com/WebKit/standards-positions/issues/74), as is Mozillas (https://github.com/mozilla/standards-positions/issues/698). It has already been implemented in Chrome 106 behind a flag.
=> add popover to no native attributes

src/rules/quoted-expressions.ts, src/test/rules/quoted-expressions_test.ts
We were incorrectly matching things like:
```ts
html`
<div>${expr}</div>
`;
```
As needing quotes when `always` was set (and not needing quotes when it wasn't set).
We now detect whether we're scanning an attribute binding or not, and limit to those expressions.
Fixes #165
=> fix: restrict quoted-expressions rule to attribute bindings

src/rules/prefer-nothing.ts, src/test/rules/prefer-nothing_test.ts
This adds a very simple suggestion to the prefer-nothing rule.
Of course, the import may not exist for `nothing` so this isn't a _fix_, rather just a suggestion.
=> feat (prefer-nothing): add suggested fix

src/rules/no-this-assign-in-render.ts, src/test/rules/no-this-assign-in-render_test.ts
Fixes #170
cc @halkeye
for anyone curious whats up here...
first of all, the tests didn't catch the bug because we were foolishly testing against `const foo = this.bar` which is a variable declaration rather than an assignment expression. so those test cases never actually hit the assignment expression logic/filtering.
once i added `let foo; foo = this.bar;` (the latter half is an assignment expression), we had a failing test.
the bug was that `foo:has([whatever] bar)` would match any `foo[whatever]` that has a descendant `bar` (🤦‍♂️ )
instead, `foo:has(.whatever bar)` will match `foo .whatever` (descendent itself) that has a descendent `bar`.
=> fix (no-this-assign-in-render): only match left side of assignments

src/rules/no-this-assign-in-render.ts, src/test/rules/no-this-assign-in-render_test.ts
The esquery we were using was too wide in that it would match a `.left` at _any_ level.
This meant the following code would match:
```ts
render() {
x = this.foo || 123;
}
```
As a `LogicalExpression` has a left just like an `AssignmentExpression`.
Since esquery doesn't support relative direct child selection (i.e. using `:has(> foo)`), we are now selecting the left side node and reporting on the parent instead.
=> fix(no-this-assign-in-render): explicit left hand side traversal

README.md, docs/rules/attribute-names.md, src/rules/attribute-names.ts, src/test/rules/attribute-names_test.ts, src/test/util_test.ts, src/util.ts
This introduces a new rule: `attribute-names`.
The rule enforces that all attributes are lowercase if the associated property is not.
For example:
```ts
class Foo extends LitElement {
@property()
camelCase = 'foo';
}
```
This will fail since the default attribute will be `camelCase`, and therefore not lowercase.
This should instead be:
```ts
@property({attribute: 'camel-case'})
```
Though in this rule, for now, the fact it is snake-case is a preference rather than being enforced by the rule.
Fixes #187 
cc @ajbrun
=> feat: new rule attribute-names

custom_types/requireindex.d.ts, src/configs/legacy-all.ts, src/configs/legacy-recommended.ts, src/index.ts, src/test/configs_test.ts
This adds support for eslint's new flat config file feature.
Supporting both systems in one config object is a rather messy situation, so we've opted here for multiple distinct configs instead.
Old style config files can continue using config objects:
```ts
{
extends: ['plugin:lit/recommended']
}
```
While new style config files can use the `flat/recommended` variety:
```ts
[
{
"files": ["*.js"],
...configs['flat/recommended']
}
]
```
Fixes #194 
cc @what1s1ove
=> feat: support flat configs

src/test/configs_test.ts
A quick change to dumb the config tests down so they basically assert against the exported structure rather than an integration-like test.
May still be worth an integration test in future.
Previously, the 2nd test case was actually passing due to an unrelated error (parse error, too low of an ecma version), which was satisfying the later assertion.
=> test: simplify config assertions

docs/rules/no-classfield-shadowing.md, package-lock.json, package.json, src/rules/no-classfield-shadowing.ts, src/test/rules/attribute-names_test.ts, src/test/rules/no-classfield-shadowing_test.ts, src/test/rules/no-property-change-update_test.ts, src/util.ts
Allows properties decorated with lit property decorators to have class fields alongside.
This loosens the strictness of the rule under the assumption you have set `useDefineForClassFields: false` in typescript.
If you use `declare` or `accessor`, those fields will already be ignored by this rule.
Examples:
```ts
// Error
class X extends LitElement {
fieldA;
static properties = {fieldA: {type: String}};
}
// Works now, errored before
class X extends LitElement {
@property()
fieldA;
}
// Worked before, works now
class X extends LitElement {
@property()
declare fieldA;
}
// Worked before, works now
class X extends LitElement {
declare fieldA;
static properties = {fieldA: {type: String}};
}
// Worked before, works now
class X extends LitElement {
@property()
accessor fieldA;
}
```
Fixes #193.
=> fix: allow decorated properties with class fields

src/rules/quoted-expressions.ts, src/test/rules/quoted-expressions_test.ts
Proposal to almost fix #209
This is not a perfect solution as there are still some false positive, but much less.
When `${...}` is preceded by `=` there will be issue, for exemple there is still issue with:
```js
html`
<x-foo attr="foo=${v}"></x-foo>
`
```
=> fix: false positive in quoted-expressions (#209)

src/rules/lifecycle-super.ts, src/rules/no-property-change-update.ts, src/rules/no-this-assign-in-render.ts, src/test/rules/attribute-names_test.ts, src/test/rules/lifecycle-super_test.ts, src/test/rules/no-property-change-update_test.ts, src/test/rules/no-this-assign-in-render_test.ts, src/util.ts
Improve algorithm to identify whether a class is a LitElement or not.
This should help with issue #148
=> feat: improve LitElement identification

docs/rules/attribute-names.md, src/rules/attribute-names.ts, src/test/rules/attribute-names_test.ts, src/util.ts
I would like to force attribute name to be the exact snake-case version of property, like PolymerJS did, I added option `strictSnakeCase` to attribute-names rule to check that.
With that option, the only possible attributes values are
```ts
@property({attribute: 'camel-case-name'})
camelCaseName: string;
// or
@property({attribute: false})
camelCaseName: string;
```
=> feat: add strictSnakeCase option to rule attribute-names

README.md, src/rules/attribute-names.ts, src/rules/lifecycle-super.ts, src/rules/no-classfield-shadowing.ts, src/rules/no-property-change-update.ts, src/rules/no-this-assign-in-render.ts, src/rules/prefer-static-styles.ts, src/test/rules/attribute-names_test.ts, src/test/rules/lifecycle-super_test.ts, src/test/rules/no-classfield-shadowing_test.ts, src/test/rules/no-native-attributes_test.ts, src/test/rules/no-property-change-update_test.ts, src/test/rules/prefer-static-styles_test.ts, src/util.ts
Fixes #148.
Adds a new option for setting element base classes, just like `eslint-plugin-wc`.
=> Add elementBaseClasses global option

src/index.ts
ESLint introduced a helper to define configs and extend from plugins. Unfortunately, this assumes each plugin is unique by reference, but that isn't the case if you imported it in ESM via `import *`.
So this introduces a default export in case someone wants to use it that way.
=> fix: export a default to satisfy eslint for now
